export const SET_USER_IS_LOGGED = 'SET_USER_IS_LOGGED';
export const RESET_USER_IS_LOGGED = 'RESET_USER_IS_LOGGED';
export const SET_IS_LOGIN_STATUS_FETCHED = 'SET_IS_LOGIN_STATUS_FETCHED';
export const RESET_IS_LOGIN_STATUS_FETCHED = 'RESET_IS_LOGIN_STATUS_FETCHED';
export const SET_IS_VERIFIED = 'SET_IS_VERIFIED';
export const RESET_IS_VERIFIED = 'RESET_IS_VERIFIED';